### ISSUE TITLE
Only shows one picture

### ISSUE THREAD

**Issue by smartsoldier** [darickc/MMM-BackgroundSlideshow#1]
I have everything setup but it just stays on one picture.

**Comment by reflect23** [comment]
I'm having the same issue.  Here's my config...
`{
                        module: "MMM-BackgroundSlideshow",
                        position: "fullscreen_below",
                        config: {
                                imagePaths: ["modules/MMM-BackgroundSlideshow/p$
                                transitionImages: true,
                                transitionSpeed: "2s",
                                randomizeImageOrder: true,
                                slideshowSpeed: 15000,
                                backgroundSize: "contain"
                        }
                },
`

**Comment by reflect23** [comment]
my tabbing is correct in the code... just having an issue with formatting in my comments here.

**Comment by darickc** [comment]
Try opening up MagicMirror in a browser.  If it is on a different computer and you are not able to connect, edit the config.js file and remove any address values and ipWhitelist values.  This is what mine looks like on my raspberry pi so I can access it from my laptop:

`address: "", 
port: 8080,
ipWhitelist: []`

Then once you have it opened in a browser open up the developer tools.  For most browsers on Windows hitting F12 will do this.  For Chrome on Mac it is command-option-i.  

Then you can look on the console tab and see any errors.  I would recommend commenting out any other modules except for the clock.  That will cut down on the amount of information shown.  Any errors should show up in red.

**Comment by reflect23** [comment]
commented out everything else but the clock and it's working great!  Thanks
so much!

Chris Sapp

**Comment by darickc** [comment]
You might try uncommenting the other modules and open it up in a browser with developer tools to see which module is causing an error.  Or uncomment them one at a time and see which one is causing the error.

**Comment by drewklein20** [comment]
I had this issue too. Out of 8 photos, only two were working. It ended up being because of the photos I was using. The pictures were taken on an iPhone and they were either live photos or taken in portrait mode. I used the photos app on my mac to convert them to PNG files and that fixed every photo.
