### ISSUE TITLE
Photos not being resized

### ISSUE THREAD

**Issue by bobcoup** [darickc/MMM-BackgroundSlideshow#105]
Hi

Great module!

I am probably doing something wrong but photos don't seem to be resized. I am running MagicMirror on an official Raspberry Pi 7" touchscreen (800x480).

Here are the settings in config.js:

{
                        module: 'MMM-BackgroundSlideshow',
                        position: 'fullscreen_below',
                        config: {
                                imagePaths: ['/mnt/photos/'],
                                recursiveSubDirectories: true,
                                transitionImages: true,
                                randomizeImageOrder: true,
                                resizeImages: true,
                                maxWidth: 800,
                                maxHeight: 480,
                                slideshowSpeed: 20000
                                }
                },
Is the maxWidth and maxHeight correct?

Thanks.

**Comment by jritsema** [comment]
Looking at the code, `resizeImages`, `maxWidth`, and `maxHeight` don't appear to be implemented at all 👎

**Comment by darickc** [comment]
They are used in [node_helper.js](https://github.com/darickc/MMM-BackgroundSlideshow/blob/master/node_helper.js)

**Comment by jritsema** [comment]
> They are used in [node_helper.js](https://github.com/darickc/MMM-BackgroundSlideshow/blob/master/node_helper.js)

Oh OK, sorry about that.  The resizing doesn't seem to work for me and I didn't see any references to it in the code, so I just assumed...

I'll try updating to the latest version and try again.

**Comment by jritsema** [comment]
> I'll try updating to the latest version and try again.

Verified that the latest version is working for me now 👍

**Comment by darickc** [comment]
Good to hear.
