### ISSUE TITLE
Enhancement: Enable Gradient on All Sides

### ISSUE THREAD

**Issue by HeyRobb** [darickc/MMM-BackgroundSlideshow#17]
Hello! First off, thank you for the amazing (and best) photo-slideshow module for Magic Mirror! I was wondering if there was a way to apply the gradient array to all four sides? This would provide a sort of vignette-effect for the photos. Any thoughts would be appreciated! Thank you again!

**Comment by darickc** [comment]
I added a new option to gradientDirection.  Use 'both' to have a vertical and a horizontal gradient.  You can set the vertical and horizontal gradients separately using 'gradient' and 'horizontalGradient'

**Comment by HeyRobb** [comment]
AWESOME!!! Thank you so much for the work on this! Woohoo!
