### ISSUE TITLE
randomizeImageOrder: false

### ISSUE THREAD

**Issue by Aldek** [darickc/MMM-BackgroundSlideshow#18]
Has anyone else used the following setting in their config.js file?

randomizeImageOrder: false,

My images don't show if I set this value to false. They work if I set the value to true, though. Unfortunately I need to play my images in order so any help to fix this would be hugely appreciated!

Ali

**Comment by darickc** [comment]
I just made a change that should fix it.  Can you update and give it a go?

**Comment by Aldek** [comment]
I've updated and it works perfectly. Thank you so much!
