### ISSUE TITLE
makeImagesGrayscale

### ISSUE THREAD

**Issue by Anool** [darickc/MMM-BackgroundSlideshow#19]
Great module - kudos. Works right, out of the box.
Does it support the "makeImagesGrayscale" property ?
If not, any plans to add that ?

**Comment by darickc** [comment]
Try putting this in your custom css file (css/custom.css):

`.backgroundSlideShow {
    filter: grayscale(100%);
}`

**Comment by Anool** [comment]
Thanks, I'll try that out and report back how it goes. Traveling until the 15th of Jan, so post that date.

**Comment by Anool** [comment]
@darickc that was perfect, and easy. Thanks.

**Comment by darickc** [comment]
Nice, glad it worked.
