### ISSUE TITLE
Install instruction?

### ISSUE THREAD

**Issue by johnnyswindle** [darickc/MMM-BackgroundSlideshow#2]
A Noob here......what are the install instructions

**Comment by darickc** [comment]
Assuming you have git installed, go to the modules directory and run

> git clone https://github.com/darickc/MMM-BackgroundSlideshow.git

Then it is easy to keep it up to date the files.  If there are any changes you can run 

> git pull

Once it is installed you can do what refect23 suggested above and edit the config.js file (this is in the config directory).  Don't forget to edit custom.css as instructed in the readme if the text is a little hard to read.

**Comment by j-funk** [comment]
This is helpful!  It might be a good idea to put in the project's main README -- I'm a noob too :D
