### ISSUE TITLE
Background image not showing

### ISSUE THREAD

**Issue by NiroDev** [darickc/MMM-BackgroundSlideshow#20]
I've tried this module along a few others (for example https://github.com/mykle1/MMM-EasyBack worked). Sadly i can't get this one running.

I've also tried to replace the inner div (div1 & div2) with an <img> attribute - as seen in the working module - without success.

The URI i get at MMM-BackgroundSlideshow.js line 154 (image.src = ...) is the same I've tested on the working module. Therefore the problem isn't related to the image path.

Changes on the other attributes doesn't solve the problem, too.

Edit: Here is my config as well as an image from FileZilla which shows the folder: https://imgur.com/a/ybGCUFH. I am using a Raspberry Pi 3b+ with Raspbian as OS.

**Comment by darickc** [comment]
I tried using that path and it gives a 404 Not Found error.  Looks like it may need to be in the modules directory.  Not sure why.  The node helper is able to see the images and pass them back, but when the browser asks for that image it gives the 404 error.  I moved the images folder to the modules folder and it worked:

`config: {
        imagePaths: ['modules/images/backgrounds'],
        transitionImages: true,
        randomizeImageOrder: true,
        recursiveSubDirectories: true
      }`

**Comment by NiroDev** [comment]
That works for me too. Might not be the final solution for this problem, but definitely an acceptable one for me at this point.

Thank you for your help! Appreciate it.
