### ISSUE TITLE
Request: Show Meta Data from pictures 

### ISSUE THREAD

**Issue by Pietske-Pieling** [darickc/MMM-BackgroundSlideshow#22]
I use my MagicMirror as a digital photo frame and this Module is working great for me. But i am always confused where and when i have taken my pictures.

So is it somehow possible to Show the meta data like Date and Location on the screen?

**Comment by gpetersen** [comment]
I'm looking into doing this now.  There's bound to be some good EXIF parsers available.  I'll be sure to share what I come up with.

**Comment by gpetersen** [comment]
@Pietske-Pieling Good news - I'm about 80% done with a new module to do just this.  What info are you most interested in?  I've got all the EXIF data available, and the folder paths & file names.  Playing with it a bit most useful to me are the folder paths and the Date/Time from the EXIF data.  The GPS location data would be a bit harder to make good use of.. Looking at options and open to ideas.

**Comment by Pietske-Pieling** [comment]
Thats great! I know that their is no easy way to Show GPS locations and i would be completly happy if i can See the Date/Time. But maybe you could add the device and the GPS coordinates.

Thanks for your efforts!

**Comment by rts58** [comment]
@gpetersen thanks for doing this.  I had to create a separate module to access the filename paths.  One thing I found is that the paths (at least in my case) were very long so I had to trim off the first 60 characters.  You may want to add some config option to trim.  I would also be interested in location.

**Comment by gpetersen** [comment]
@Pietske-Pieling & @rts58 
I've uploaded some working code, including the GPS Geoname functionality, let me know what you think!

There's two modules. I haven't actually run it on Linux yet, just on my setup that runs on Windows, so there may be some issues.
https://github.com/gpetersen/MMM-BackgroundSlideshow is my fork of the BackgroundSlideshow with the new functionality, and in addition it will also send a notification when the image is updated to allow my second module: https://github.com/gpetersen/MMM-BackgroundSlideshowInfo to know the image has changed and to get the image metadata and show it.
Please test them out and submit any bugs over there. If they work well I'll request a Pull.
