### ISSUE TITLE
backgroundSize:cover problem

### ISSUE THREAD

**Issue by bekirs** [darickc/MMM-BackgroundSlideshow#24]
backgroundSize: cover is a default value ( i also added configuration) but still there is blank area left and right of the screen. How can i solve it ?

**Comment by bekirs** [comment]
also when i run the Magir Mirror, after a short while screen goes black, I cannot see anything on the screen, only black

**Comment by darickc** [comment]
You can try to open it in a browser and see what is being set for the style.  I prefer Chrome for this.  With it open in your browser, right click and select "Inspect".  You should something like in the image.  Make sure background-size is set to cover.

![inspect](https://user-images.githubusercontent.com/14807076/52368145-fb8ef380-2a0a-11e9-831f-ca84698fe5a8.jpg)
