### ISSUE TITLE
Black bar when using MMM-carousel /w slide navigation

### ISSUE THREAD

**Issue by tvaneynde** [darickc/MMM-BackgroundSlideshow#3]
Hi

i recently installed you're module (wich is great btw), but i also have MMM-carousel /w slide navigation, and i get this weird black bar.

![2018-08-24-183341_1280x1024_scrot](https://user-images.githubusercontent.com/18744978/44596515-c2e8be00-a7cc-11e8-86c8-78f4c6252911.png)

Any fixes?

Tomas

**Comment by tvaneynde** [comment]
Hi

Thanks a lot for the response.

But i don’t really know a lot of CSS so i’m kinda stuck now.
Sorry if i’m being annoying, but i’m a noob a this.

Tomas

**Comment by darickc** [comment]
What does your config for the carousel look like?  I have installed it, but I don't see the dots.  Is this the one you have installed? https://github.com/barnabycolby/MMM-Carousel

**Comment by tvaneynde** [comment]
Hi

You have to install this one https://github.com/shbatm/MMM-Carousel.
This is my carousel config:

`	{
			module: 'MMM-Carousel',
			position: 'bottom_bar', // Required only for navigation controls
			config: {
				transitionInterval: 0,
				mode: 'slides',
				showPageIndicators: true,
				showPageControls: true,
				slides: [
					['calendar', 'compliments', 'clock', 'alert', 'newsfeed', 'weatherforecast', 'currentweather', 'MMM-WeeklySchedule', 'MMM-BackgroundSlideshow'],
					['MMM-OnScreenMenu', 'MMM-AirQuality', 'MMM-BackgroundSlideshow'],
					['MMM-iFrame', 'mm-music-player', 'MMM-BackgroundSlideshow'],
					['MMM-Remote-Control', 'MMM-RemoteControl-Repository', 'MMM-Admin-Interface', 'MMM-connection-status', 'MMM-NetworkConnection', 'MMM-SystemStats', 'MMM-BackgroundSlideshow']
				],
				keyBindingsMode: "DEFAULT",
				keyBindings: {
					NextSlide: "ArrowRight",
					PrevSlide: "ArrowLeft",
					Slide0: "Home",
				}
			}
		},
`

**Comment by tvaneynde** [comment]
Hi

I’m going to uninstall the carrousel module and instead install Hello-Lucy.
You van close this issue.
Thanks for your time!

Tomas
