### ISSUE TITLE
Stopped working after last update

### ISSUE THREAD

**Issue by esjani** [darickc/MMM-BackgroundSlideshow#41]
Hi!

I updated to the most recent version through the MagicMirror Remote Control module and it stopped working. No errors while starting the MagicMirror, nothing changed in the config.js, but no images are shown.

Can I post somehow debug information?

Thanks in advance!

**Comment by esjani** [comment]
It could be something with the new version:
- clean install of MagicMirror
- clean install of BackgroundSlideshow
- default config.js, with copy-paste example for BackgroundSlideshow
- no reinstall of the whole pi

No images from the example directory are shown. I hope this helps a little!

**Comment by jorgenp** [comment]
I get the same behavior. Can I increase debug info for this module somehow?
The only thing I found is the output in the pm2 log under ~/.pm2/logs/MagicMirror-out.log. And the only thing in that log file for this module is:
...
Starting MagicMirror: v2.8.0
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-BackgroundSlideshow
...
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-BackgroundSlideshow
...

No error messages in .pm2/logs/MagicMirror-error.log.

**Comment by darickc** [comment]
I reverted the pull requests I merged earlier.  Can you see if you are continuing to have issues?

**Comment by itachiomar** [comment]
Hi I just updated to the latest version and got a black screen

**Comment by darickc** [comment]
I'm testing it now and don't have any problems.  I've updated the MM code and this code.  Are you getting any errors in the browser?

**Comment by darickc** [comment]
I also just updated it on my raspberry pi and it seems OK too.

**Comment by itachiomar** [comment]
No errors in the browser

**Comment by darickc** [comment]
Can you comment out everything but the BackgroundSlideshow and the clock?  Perhaps it is something else that is causing the error.  That may determine if it is this or something else.

**Comment by itachiomar** [comment]
Ok will do

**Comment by itachiomar** [comment]
Got it working the problem was with electron so I did a re install of the mm

**Comment by darickc** [comment]
Great!

**Comment by esjani** [comment]
I got an update this morning, after that everything works again fine!

**Comment by benlinton** [comment]
I tested the changes in Chrome and they were working fine.  Maybe the opacity needs to be a string rather than a number is some cases?  Other than that, I don't see anything that could be a problem since the changes were so minor.
