### ISSUE TITLE
Frequency of image change increases with every connected client

### ISSUE THREAD

**Issue by fr0nk** [darickc/MMM-BackgroundSlideshow#48]
**Issue:**
When only a single client (browser) is connected to the MagicMirror, everything works fine. But open another tab with the MagicMirror Url and the images change in higher frequency in all tabs. Open a few more and the background image changes like crazy.

**Config:**
Default installation with default settings, only changed `transitionImages` to `false` so the image change is visible with high frequency.

**Comment by ryanm7780** [comment]
I'm seeing this same behavior.  I have 3 tablets in the house all looking at a central server-only MagicMirror instance and the images just flash like crazy on each tablet.

**Comment by dushyantahuja** [comment]
I see the same issue, is there any way to avoid this?

**Comment by crazyscot** [comment]
The issue seems to arise because the timer is instantiated once on every client (by `MMM-BackgroundSlideshow.js`) , as opposed to just once (if it were to live in `node_helper.js`).
