### ISSUE TITLE
Request: use subfolders

### ISSUE THREAD

**Issue by kerijn** [darickc/MMM-BackgroundSlideshow#5]
Any chance for an enhancement of this module so that is automatically looks for picturs in subfolders and randomly shows pictures?

It works great by the way!

**Comment by darickc** [comment]
I will see what I can do.  Just need to find the time.

**Comment by darickc** [comment]
This is done.  Sorry it took so long.

**Comment by kerijn** [comment]
Thank you very much! I will try it out and let you know if it works!

**Comment by kerijn** [comment]
Works great! Thanks!
