### ISSUE TITLE
Opacity changes

### ISSUE THREAD

**Issue by Plainbroke** [darickc/MMM-BackgroundSlideshow#54]
can barely read on screen modules 
["calendar"],
["MMM-ATM"],
["calendarH"],
["MMM-Fortune"],
["MMM-DailyQuote"],
["MMM-Gas"],
["MMM-CloneWarsQuotes"],
["MMM-Globe"],
["MMM-icanhazdadjoke"],
is there a way to make the pictures in the background dimmer?

**Comment by smartroad** [comment]
I use: `gradient: [ "rgba(0,0,0,0.8) 0%", "rgba(0,0,0,0.8) 100%"],` change the 0.8 higher for darker or lower for lighter

**Comment by Plainbroke** [comment]
That's what I finally figured out. 
Thanks for the information.
