### ISSUE TITLE
Scale image size

### ISSUE THREAD

**Issue by vulcandragon** [darickc/MMM-BackgroundSlideshow#64]
Is there a way to scale the image size to that the image fits the screen. Tall images scale to the max height of the screen, or pre-determined size. And/or wide images scale to the max width of the screen, or pre-determined size.

**Comment by darickc** [comment]
You want to use the backgroundSize setting:
The sizing of the background image. Values can be:
cover: Resize the background image to cover the entire container, even if it has to stretch the image or cut a little bit off one of the edges.
contain: Resize the background image to make sure the image is fully visible

**Comment by vulcandragon** [comment]
Nevermind. I'm stupid and found the settings...

Thank you
