### ISSUE TITLE
Black screen since last update

### ISSUE THREAD

**Issue by mcnahum** [darickc/MMM-BackgroundSlideshow#72]
This morning I applied the last update ( May 11 2020) and since then all seems ok ... except that no photo are loaded ... I just have a black screen instead... nothing else changed on the RPi, photo are there... no error message, nothing in the log ... all other modules are there.

Any clue how to debug?

edit: if I start MM in dev mode, I can see "No image to display" on the logs...

Edit2: Reverting to previous code is fixing the issue ... someone need to look what was breaking it...

**Comment by darickc** [comment]
I reverted the changes.  I'll have to do more testing.  Sorry for the issues.

**Comment by mcnahum** [comment]
Thanks all good now

**Comment by mcnahum** [comment]
ok ... so not sure what happen but it's loaded ( slow) 1 photo but transition to black screen after...

**Comment by mcnahum** [comment]
ok reboot and seams ok ... let wait ... and I'm closing in the mean time
