### ISSUE TITLE
Changing the language given by the config.js

### ISSUE THREAD

**Issue by Abert2002** [darickc/MMM-BackgroundSlideshow#74]
After installing and running the module (its working like a charm Thank you for this!) my day at the clock is changed from german to english. There was _Donnerstag, 14. Mai_ instead of _Thursday, May 14_ 
Any idea how to solve this?

![Day](https://user-images.githubusercontent.com/33970832/81983766-2fa48b80-9634-11ea-9405-57c36ecc5b49.jpg)

**Comment by darickc** [comment]
Do you have the latest code?  I changed the reference to moment.js hoping it would fix this issue.  Does line 133 of MMM-BackgroundSlideshow.js look like this?

`return ['modules/' + this.name + '/node_modules/exif-js/exif.js', 'modules/' + this.name + '/node_modules/lodash/lodash.js', 'moment.js'];`

**Comment by Abert2002** [comment]
I just made a fresh installation. Now its working! :) Thank you for this!

![Day](https://user-images.githubusercontent.com/33970832/82091403-90e16300-96f7-11ea-8757-5184b6b9cdb0.jpg)
