### ISSUE TITLE
Black screen after a while

### ISSUE THREAD

**Issue by Carote** [darickc/MMM-BackgroundSlideshow#87]
Hi everyone,

I'm very interested in this module. I've added it to my MM and it works fine for ... a while. After random time working, MM is only displaying complete black mirror with only mouse pointer. When restarting MM, everything is again working fine for a while and so on.

I've disabled this BackgroundSlideshow module, and everything is working fine for several days. So I'm wondering what can be the issue (sw / hw / wrong compatibility) ? I've checked CPU load and RAM free : less than 1 and 25% free, similar with module enable or disable

I'm using RPi4. I've checked some log files (not an expert for this) and nothing particular when the issue appears
Did someone noticed this issue ? Have you got any tips for me ?

Thanks very much for your help, I really would like to use this module... !

**Comment by KamiSchami** [comment]
Hi, i have the same problem... 
🙈

**Comment by petitemuse** [comment]
i also do have the same problem: The mirror turns black with only the mouse. any solution?

**Comment by dresch27** [comment]
same here

**Comment by dresch27** [comment]
I've attempted every workaround I can find and still get a black screen. Is this modules not longer being supported? It would be unfortunate, as it is a really great module.

**Comment by darickc** [comment]
It isn't maintained much by me any more,  though if there are pull requests I usually accept and merge them in.  My raspberry pi died a while back and just recently got a new one, but decided to go a different direction with it and haven't been running Magic Mirror on it.  I have some ideas that might help, but need to find some time to implement them.  If anyone comes up with a fix before then, I would be glad to merge it in.

**Comment by openedhardware** [comment]
Same problem here.
Started MagicMirror in dev mode with `npm run start dev` but no error message on the console.

Any idea?

**Comment by MystaraTheGreat** [comment]
Same error here too

**Comment by scottdrichards** [comment]
I was having the same issue and it went away when I made a new images folder with just a dozen or so images in it instead of the large image folder I had been using. I had figured that my SD card was corrupted and when it loaded an image, it would crash but seeing others with the same problem maybe that wasn't the case.

Even though it now seems to work again, I do notice that the entire MM blacks out (time, calendar, everything) for 1/4 of a second during transitions every now and then.  My new theory is that there is an error for when all the pictures have been viewed and it resets. Perhaps if you have a large number of pictures, this resetting gets in the way of other processes and it hangs.

**Comment by scottdrichards** [comment]
https://github.com/darickc/MMM-BackgroundSlideshow/issues/90
This seems to have a detailed explanation of what goes wrong.

**Comment by Carote** [comment]
As shared by scottdrichards, a “solution” is available in #90 : you can use MMM-RandomPhoto from skuethe which seems to work fine for me (but with less options) or you can add MMM-WatchDog with PM2 process manager. It doesn’t fix the issue, but it can restart PM2 automatically when freezing. I have been using it for two days in a row now and I didn’t noticed any new issue
Other fix that I used until now : use a crontab to reboot the Pi everyday at 6pm with high changing duration between two pictures. MM was able to run fine this way
