### ISSUE TITLE
EXIF orientation ignored

### ISSUE THREAD

**Issue by M4Rv** [darickc/MMM-BackgroundSlideshow#9]
Thanks for the module. It is working great for me except for one thing:

Photos are not always in correct orientation (upside-down / sideways). It seems the module is not taking the EXIF information of the jpg files into consideration.

**Comment by darickc** [comment]
Magic Mirror uses the browser and browsers don't support the EXIF information.  There is css for this (image-orientation: from-image;) but it is only supported in FireFox and partial support in iOS Safari (https://caniuse.com/#search=image-orientation).  My suggestion is to rotate them manually.

**Comment by M4Rv** [comment]
Did the manual rotation.
Thanks for the explanation though!
