### ISSUE TITLE
Vignette?

### ISSUE THREAD

**Issue by pepeuDotCom** [darickc/MMM-BackgroundSlideshow#93]
Hehey, I might be doing something nooby here, but there is this vignette in the corners. Am I missing something, or can I do something simple to get rid of it?

**Comment by darickc** [comment]
You can add the gradient option to the config settings.  Setting it to something like [ "rgba(0, 0, 0, 0) 0%"] should work I think.  This was just meant to make the text more readable when the background is a light color.

**Comment by pepeuDotCom** [comment]
Is it there by default? I just want to show the pictures, nothing else.

**Comment by darickc** [comment]
Yes, the default value is [ "rgba(0, 0, 0, 0.75) 0%", "rgba(0, 0, 0, 0) 40%", "rgba(0, 0, 0, 0) 80%", "rgba(0, 0, 0, 0.75) 100%" ].  Just follow the instructions on the main page for adding config options.  It would look something like this:

`modules: [
  {
    module: 'MMM-BackgroundSlideshow',
    position: 'fullscreen_below',
    config: {
      imagePaths: ['modules/MMM-BackgroundSlideshow/exampleImages/'],
      transitionImages: true,
      randomizeImageOrder: true,
      gradient: [ "rgba(0, 0, 0, 0) 0%"]
    },
  },
];`
